name: globalbrain_mobile
description: Global Brain mobile app - AI study companion for students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  
  # Navigation
  go_router: ^12.1.3
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  
  # File Handling
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  mime: ^1.0.4
  
  # UI Utilities
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # Date & Time
  intl: ^0.19.0
  
  # Loading & Progress
  flutter_spinkit: ^5.2.0
  
  # Toast & Notifications
  fluttertoast: ^8.2.4
  
  # Image Handling
  image_picker: ^1.0.7
  
  # Animations
  lottie: ^2.7.0
  
  # Utils
  equatable: ^2.0.5
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700