name: global_brain_student
description: Your AI study partner that organizes notes, tutors you at your level, and tracks progress — in minutes a day.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  lottie: ^2.7.0

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # File Handling
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0

  # Real-time Communication
  web_socket_channel: ^2.4.0

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700